{
 "title": "Cluster Nodearray Level Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{instance=\"$instance\"}, gpu)"
    }
   },
   {
    "name": "powerlimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"}"
    }
   },
   {
    "name": "templimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\",instance=\"$instance\"}"
    }
   },
   {
    "name": "physicalhost",
    "query": {
     "query": "label_values(dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"},physical_host)"
    }
   },
   {
    "name": "nodearray",
    "label": "nodearray",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},nodearray)"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Average Uptime",
   "type": "stat",
   "description": "Average Time Nodearray $nodearray has been up across all nodes",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (nodearray)(node_time_seconds{nodearray=~\"^$nodearray$\", cluster=\"$cluster\"} - node_boot_time_seconds{nodearray=~\"^$nodearray$\", cluster=\"$cluster\"})",
     "legendFormat": "{{nodearray}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Heat Map (avg)",
   "type": "state-timeline",
   "description": "Average CPU Utilization Heat Map for nodearray $nodearray",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (nodearray) (rate(node_cpu_seconds_total{nodearray=~\"^$nodearray$\",mode=\"idle\",cluster=\"$cluster\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "gauge",
   "description": "Average % of Filesystem Used by Nodearray $nodearray",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(100 - avg by (nodearray)(node_filesystem_avail_bytes{nodearray=~\"^$nodearray$\",mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / avg by (nodearray)(node_filesystem_size_bytes{nodearray=~\"^$nodearray$\",mountpoint=\"/\",fstype!=\"rootfs\",cluster=\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "description": "Average CPU Utilization for Nodearray $nodearray",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (nodearray) (rate(node_cpu_seconds_total{nodearray=~\"^$nodearray$\",mode=\"idle\",cluster=\"$cluster\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Average Disk I/O Utilization for Nodearray $nodearray",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (nodearray)(irate(node_disk_io_time_seconds_total{nodearray=~\"^$nodearray$\",device=~\"$diskdevices\", cluster=\"$cluster\"} [$__rate_interval]))",
     "legendFormat": "{{nodearray}} {{device}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Average Memory Utilization for Nodearray $nodearray",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - avg by (nodearray)(node_memory_memavailable_bytes{nodearray=~\"^$nodearray$\", cluster=\"$cluster\"}) / avg by (nodearray)(node_memory_memtotal_bytes{nodearray=~\"^$nodearray$\",cluster=\"$cluster\"})))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (nodearray)(irate(node_mountstats_nfs_total_read_bytes_total{nodearray=~\"^$nodearray$\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} {{export}} - read"
    },
    {
     "expr": "avg by (nodearray)(irate(node_mountstats_nfs_total_write_bytes_total{nodearray=~\"^$nodearray$\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} {{export}} - write"
    }
   ]
  },
  {
   "title": "Memory Major Page Faults",
   "type": "timeseries",
   "description": "Processes waiting on disk-backed memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg by (nodearray)(irate(node_vmstat_pgmajfault{nodearray=~\"^$nodearray$\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ethernet Throughput (RX/TX)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (nodearray)(rate(node_network_receive_bytes_total{nodearray=~\"^$nodearray$\",device='eth0',cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} - receive"
    },
    {
     "expr": "avg by (nodearray)(rate(node_network_transmit_bytes_total{nodearray=~\"^$nodearray$\",device='eth0',cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} - transmit"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": " avg by (nodearray,device)(irate(node_disk_read_bytes_total{nodearray=~\"^$nodearray$\",device=~\"$diskdevices\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} {{device}} -read"
    },
    {
     "expr": "avg by (nodearray,device)(irate(node_disk_written_bytes_total{nodearray=~\"^$nodearray$\",device=~\"$diskdevices\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{nodearray}} {{device}}  - write"
    }
   ]
  }
 ]
}