{
 "title": "Cluster View (Time Series)",
 "description": "Provides overview of cluster CPU, GPU, IB & NVLink metrics ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job ID", "query": { "query": "" } },
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "Operation",
    "query": "Average : 1, Minimum : 2,  Maximum : 3"
   }
  ]
 },
 "panels": [
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Load (Load1 / Core Count) ($Operation)",
   "type": "timeseries",
   "description": "Normalized CPU Load (Load1 / Core Count) ($Operation)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(avg by(instance) (node_load1{cluster=\"$cluster\"}) / on(instance) count by (instance) (group by (instance, cpu) (node_cpu_seconds_total{cluster=\"$cluster\"}))) * ($Operation== bool 1) + (min by(instance) (node_load1{cluster=\"$cluster\"}) / on(instance) count by (instance) (group by (instance, cpu) (node_cpu_seconds_total{cluster=\"$cluster\"}))) * ($Operation== bool 2) + (max by(instance) (node_load1{cluster=\"$cluster\"}) / on(instance) count by (instance) (group by (instance, cpu) (node_cpu_seconds_total{cluster=\"$cluster\"}))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - 1m"
    }
   ]
  },
  {
   "title": "Filesystem Usage ($Operation)",
   "type": "timeseries",
   "description": "Filesystem usage by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"}))) * ($Operation== bool 1) + (min by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"}))) * ($Operation== bool 2) + (max by(instance) (100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"}))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation on CPU utilization across all nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval])))))  *  ($Operation== bool 1)  + (min by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval])))))  *  ($Operation== bool 2)  + (max by(instance) (100 * (1 - avg by(instance, cpu) (rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__rate_interval])))))  *  ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Clock ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM CPU Clock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (node_cpu_frequency_hertz{cluster=\"$cluster\"})/ 1000000)  *  ($Operation== bool 1)  + (min by(instance) (node_cpu_frequency_hertz{cluster=\"$cluster\"})/ 1000000)  *  ($Operation== bool 2)  + (max by(instance) (node_cpu_frequency_hertz{cluster=\"$cluster\"})/ 1000000)  *  ($Operation== bool 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation on Memory utilization across all nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (100 * (1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\"})))) * ($Operation== bool 1) + (min by(instance) (100 * (1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\"})))) * ($Operation== bool 2) + (max by(instance) (100 * (1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\"})))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Major Page Faults ($Operation)",
   "type": "timeseries",
   "description": "Memory Major Page Faults ($Operation)\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_vmstat_pgmajfault{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_vmstat_pgmajfault{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_vmstat_pgmajfault{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Available Memory ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM Available Memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "(avg by(instance) (node_memory_memavailable_bytes{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (node_memory_memavailable_bytes{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (node_memory_memavailable_bytes{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethernet Throughput (RX/TX) ($Operation)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface by Node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device='eth0', cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_network_receive_bytes_total{device='eth0', cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_network_receive_bytes_total{device='eth0', cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(sum by(instance) (rate(node_network_transmit_bytes_total{device='eth0',cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_network_transmit_bytes_total{device='eth0',cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_network_transmit_bytes_total{device='eth0',cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization ($Operation)",
   "type": "timeseries",
   "description": "Disk I/O Utilization by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Throughput ($Operation)",
   "type": "timeseries",
   "description": "Disk Throughput(read & write) by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(avg by(instance) (irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_disk_written_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  {
   "title": "NFS I/O Operations ($Operation)",
   "type": "timeseries",
   "description": "NFS I/O Operations by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(avg by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^READ$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(avg by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_operations_requests_total{operation=~\"^WRITE$\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  {
   "title": "NFS Throughput ($Operation)",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_mountstats_nfs_total_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_total_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_total_read_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "(sum by(instance) (irate(node_mountstats_nfs_total_write_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (irate(node_mountstats_nfs_total_write_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (irate(node_mountstats_nfs_total_write_bytes_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  },
  { "title": "GPU Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "GPU Utilization ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_GPU_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization ($Operation)",
   "type": "timeseries",
   "description": "Average of VM GPU device Memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEM_COPY_UTIL{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SM Clock ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device SM Clock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_SM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_SM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_SM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Clock ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Clock",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEM_CLOCK{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperature ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_GPU_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Temperature ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_MEMORY_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_MEMORY_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_MEMORY_TEMP{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Usage ($Operation)",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU Power",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(avg by(instance) (DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\"}))  *  ($Operation== bool 1)  + (min by(instance) (DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\"}))  *  ($Operation== bool 2)  + (max by(instance) (DCGM_FI_DEV_POWER_USAGE{cluster=\"$cluster\"}))  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption ($Operation)",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "(avg by(instance) (dcgm_fi_dev_total_energy_consumption{cluster=\"$cluster\"})/ 10^3)  *  ($Operation== bool 1)  + (min by(hostname) (dcgm_fi_dev_total_energy_consumption{cluster=\"$cluster\"})/ 10^3)  *  ($Operation== bool 2)  + (max by(instance) (dcgm_fi_dev_total_energy_consumption{cluster=\"$cluster\"})/ 10^3)  *  ($Operation== bool 3) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last XID Code Present ($Operation)",
   "type": "table",
   "description": "Last XID Code Present(> 0 indicates XID error)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Throttle Code ($Operation)",
   "type": "table",
   "description": "Last Throttle Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_EVENT_REASONS{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_sbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_dbe_agg_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_sbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_ecc_dbe_vol_total{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time ($Operation)",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_thermal_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_thermal_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_thermal_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time ($Operation)",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_power_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_power_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_power_violation{cluster=\"$cluster\"}[$__rate_interval]) / 1e9)) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Infiniband Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "IB Link Status",
   "type": "timeseries",
   "description": "IB link state by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (instance) (node_infiniband_physical_state_id{device!=\"mlx5_an0\", cluster=\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last IB Link Flap",
   "type": "table",
   "description": "Last IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "clamp_max(increase(node_infiniband_link_downed_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Throughput ($Operation)",
   "type": "timeseries",
   "description": "IB (RX+TX) throughput ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_data_received_bytes_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_data_transmitted_bytes_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "IB Port Receive Errors ($Operation)",
   "type": "timeseries",
   "description": "Port receive errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(node_infiniband_port_errors_received_total{device!=\"mlx5_an0\", cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Constraint Errors ($Operation)",
   "type": "timeseries",
   "description": "IB port constraint errors by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(node_infiniband_port_constraint_errors_received_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Transmit Wait ($Operation)",
   "type": "timeseries",
   "description": "IB port transmit wait by node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(node_infiniband_port_transmit_wait_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IB Port Discards ($Operation)",
   "type": "timeseries",
   "description": "IB port discards by node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(node_infiniband_port_discards_transmitted_total{device!=\"mlx5_an0\",cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "NVLink Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Last NVLink Recovery Failed Event ($Operation)",
   "type": "table",
   "description": "Last NVLink Recovery Failed Event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    {
     "expr": "clamp_max(increase(dcgm_fi_dev_nvlink_count_link_recovery_failed_events{cluster=\"$cluster\"}[$__rate_interval]), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Integrity Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of times that the count of local errors exceeded the set threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NVLink Throughput ($Operation)",
   "type": "timeseries",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(dcgm_fi_prof_nvlink_rx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - receive "
    },
    {
     "expr": "(avg by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (rate(dcgm_fi_prof_nvlink_tx_bytes{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "Link RX Errors ($Operation)",
   "type": "timeseries",
   "description": "Total number of packets with errors Rx on a link",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_rx_errors{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Port TX Discards ($Operation)",
   "type": "timeseries",
   "description": "Total number of TX error packets that were discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "(avg by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 1) + (min by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 2) + (max by(instance) (increase(dcgm_fi_dev_nvlink_count_tx_discards{cluster=\"$cluster\"}[$__rate_interval]))) * ($Operation== bool 3)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}