{
 "title": "GPU Device Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{instance=\"$instance\"}, gpu)"
    }
   },
   {
    "name": "powerlimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"}"
    }
   },
   {
    "name": "templimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\",instance=\"$instance\"}"
    }
   },
   {
    "name": "physicalhost",
    "query": {
     "query": "label_values(dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"},physical_host)"
    }
   },
   {
    "name": "nodearray",
    "label": "nodearray",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},nodearray)"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "GPU Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{instance=~\"$instance\", cluster=\"$cluster\", gpu=\"0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization Heat Map",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{instance=~\"^$instance$\", cluster=\"$cluster\", gpu=~\"$gpu\"}",
     "legendFormat": "{{instance}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Average Power Usage",
   "type": "gauge",
   "description": "Average Power Usage (Power Draw/Max Power Limit)",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance)((dcgm_fi_dev_power_usage{instance=~\"^$instance$\",cluster=\"$cluster\"} / dcgm_fi_dev_power_mgmt_limit{instance=~\"^$instance$\",cluster=\"$cluster\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Temperature Usage ",
   "type": "gauge",
   "description": "Average GPU Temperature (GPU Temp/Max Operating Temp) ",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)((dcgm_fi_dev_gpu_temp{instance=~\"^$instance$\",cluster=\"$cluster\"} / dcgm_fi_dev_gpu_max_op_temp{instance=~\"^$instance$\",cluster=\"$cluster\"}) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU XID Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (gpu,instance) (dcgm_fi_dev_xid_errors{instance=~\"^$instance$\", cluster=\"$cluster\"})",
     "legendFormat": "{{instance}} GPU - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{instance=~\"^$instance$\", gpu=~\"$gpu\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_memory_temp{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Last GPU XID Code",
   "type": "table",
   "description": "Last XID Code Present(> 0 indicates XID error)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{instance=~\"^$instance$\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last GPU Throttle Code",
   "type": "table",
   "description": "Last GPU Throttle Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_EVENT_REASONS{instance=~\"^$instance$\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_temp{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_agg_total{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_usage{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_agg_total{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_thermal_violation{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_vol_total{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_power_violation{instance=~\"^$instance$\", gpu=~\"$gpu\",cluster=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  }
 ]
}