{
 "title": "GPU Device View",
 "description": "dcgm_fi_dev_* Counters",
 "tags": [ "Moneo Refined" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, microsoft.resourcegroupname)"
    }
   },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info,vm_instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{vm_instance=\"$instance\"}, gpu)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\", \"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_copy_util{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\", \"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_sm_clock{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_clock{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_temp{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_memory_temp{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_usage{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_total_energy_consumption{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"} / 10^3",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Last GPU XID Code",
   "type": "table",
   "description": "Last XID Code Present(> 0 indicates XID error)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{vm_instance=~\"^$instance$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ECC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_agg_total{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_agg_total{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_vol_total{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_vol_total{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "GPU Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Last GPU Throttle Code",
   "type": "table",
   "description": "Last GPU Throttle Code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_EVENT_REASONS{vm_instance=~\"^$instance$\",\"microsoft.resourcegroupname\"=\"$cluster\"}",
     "legendFormat": "{{vm_instance}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_thermal_violation{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_power_violation{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "NVLink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Last NVLink Recovery Failed Event",
   "type": "table",
   "description": "Last NVLink Recovery Failed Event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "clamp_max(increase(dcgm_fi_dev_nvlink_count_link_recovery_failed_events{vm_instance=~\"^$instance$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval]), 1)",
     "legendFormat": "{{vm_instance}}"
    }
   ]
  },
  {
   "title": "Link Integrity Errors",
   "type": "timeseries",
   "description": "Total number of times that the count of local errors exceeded the set threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "NVLink Throughput (RX/TX)",
   "type": "timeseries",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(dcgm_fi_prof_nvlink_rx_bytes{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}} - receive"
    },
    {
     "expr": "rate(dcgm_fi_prof_nvlink_tx_bytes{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}} - transmit"
    }
   ]
  },
  {
   "title": "Link RX Errors",
   "type": "timeseries",
   "description": "Total number of packets with errors Rx on a link",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_rx_errors{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Port TX Discards",
   "type": "timeseries",
   "description": "Total number of TX error packets that were discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_tx_discards{vm_instance=~\"^$instance$\", gpu=~\"^$gpu$\",\"microsoft.resourcegroupname\"=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}