{
 "title": "Node Level Health Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{instance=\"$instance\"}, gpu)"
    }
   },
   {
    "name": "powerlimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"}"
    }
   },
   {
    "name": "templimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\",instance=\"$instance\"}"
    }
   },
   {
    "name": "physicalhost",
    "query": {
     "query": "label_values(dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"},physical_host)"
    }
   }
  ]
 },
 "panels": [
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode='idle', instance=~\"^$instance$\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (instance)(100 - (node_filesystem_avail_bytes{instance=~\"^$instance$\",mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{instance=~\"^$instance$\",mountpoint=\"/\",fstype!=\"rootfs\",cluster=\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time Node has been up",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(node_time_seconds{instance=\"$instance\", cluster=\"$cluster\"} - node_boot_time_seconds{instance=\"$instance\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"^$instance$\", cluster=\"$cluster\"} / node_memory_memtotal_bytes{instance=~\"^$instance$\", cluster=\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Disk I/O Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"^$instance$\",device=~\"$diskdevices\", cluster=\"$cluster\"} [$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Memory Major Page Faults",
   "type": "timeseries",
   "description": "Processes waiting on disk-backed memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_total_read_bytes_total{instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{export}} - read"
    },
    {
     "expr": "irate(node_mountstats_nfs_total_write_bytes_total{instance=~\"^$instance$\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{export}} - write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"^$instance$\",device=~\"$diskdevices\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} -read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"^$instance$\",device=~\"$diskdevices\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}} - write"
    }
   ]
  },
  {
   "title": "Ethernet Throughput (RX/TX)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device='eth0', instance=~\"^$instance$\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{device='eth0', instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  }
 ]
}