{
 "title": "Node View",
 "description": "Node Exporter System Metrics",
 "tags": [ "Moneo Refined" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - avg by (instance, cpu) (rate(node_cpu_seconds_total{mode='idle', instance=~\"$instance\", cpu=~\"$cpu\", cluster=\"$cluster\"}[$__rate_interval]))))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "timeseries",
   "description": "CPU Clock Speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"$instance\", cpu=~\"$cpu\", cluster=\"$cluster\"} / 1000000",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Node Load (Load1 / Core Count)",
   "type": "timeseries",
   "description": "Node Load (Load1 / Core Count)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "scalar(node_load1{cluster=\"$cluster\", instance=\"$instance\"}) * 100 / count(count(node_cpu_seconds_total{cluster=\"$cluster\", instance=\"$instance\"}) by (cpu))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"$instance\", cluster=\"$cluster\"} / node_memory_memtotal_bytes{instance=~\"$instance\",cluster=\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"$instance\",cluster=\"$cluster\"} / node_memory_memtotal_bytes{instance=~\"$instance\",cluster=\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Major Page Faults",
   "type": "timeseries",
   "description": "Processes waiting on disk-backed memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Ethernet Throughput (RX/TX)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device='eth0', instance=~\"$instance\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{device='eth0', instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Filesystem Space",
   "type": "timeseries",
   "description": "Filesystem size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",device!~\"rootfs\"} - node_filesystem_avail_bytes{instance=\"$instance\",device!~\"rootfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Operations",
   "type": "timeseries",
   "description": "Disk I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",device=~\"$diskdevices\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} - reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - writes completed"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Disk I/O Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$instance\",device=~\"$diskdevices\",cluster=\"$cluster\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$instance\",device=~\"$diskdevices\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$instance\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  { "title": "NFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "NFS I/O Operations",
   "type": "timeseries",
   "description": "NFS I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\", operation=~\"^READ$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}s completed"
    },
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=\"$instance\", operation=~\"^WRITE$\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}s completed"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_total_read_bytes_total{instance=\"$instance\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - read"
    },
    {
     "expr": "irate(node_mountstats_nfs_total_write_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{export}} - write"
    }
   ]
  }
 ]
}